### ISSUE TITLE
Request for OpenRoad Version Used in the Contest

### ISSUE THREAD

**Issue by shao-chien-lu** [liangrj2014/ISPD25_contest#2]
Since OpenRoad is updated frequently, could you please provide the version of OpenRoad used for this contest to prevent any version issues from affecting the evaluation?

**Comment by liangrj2014** [comment]
Thanks for the question! Please use our forked version of OpenRoad: https://github.com/liangrj2014/OpenROAD_ISPD25

**Comment by shao-chien-lu** [comment]
Okay. Thanks.
