### ISSUE TITLE
Question about the output format

### ISSUE THREAD

**Issue by cai-zhi-jie** [liangrj2014/ISPD25_contest#3]
As in ISPD2025, the output should be within the original layout coordinate system. 
Could we assume that all coordinates are the center of one of the Gcells? 
Or can we assign a coordinate not in the center of one Gcell, like the results in detailed routing, as long as the results are connected and cover all pins?
Would the detailed-routing-style result lead to a less congested metric? 
Should this detailed-routing-style result be prohibited?

**Comment by liangrj2014** [comment]
Thanks for the questions!  The output should be GCell-based, with routing segments either fully covering entire GCells or not overlapping them at all. You can find some illustrations here: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/discussions/2197
