### ISSUE TITLE
Question about the power net

### ISSUE THREAD

**Issue by cai-zhi-jie** [liangrj2014/ISPD25_contest#5]
I have noticed that there is information about the VDD and VSS net in the def file.
![image](https://github.com/user-attachments/assets/05c82221-1d01-475e-a795-dfbf0a3236e5)

But the contest introduction says that "for the sake of simplicity, these circuits do not incorporate power gird or clock tree routing."
![image](https://github.com/user-attachments/assets/ba65b3f7-e589-4d7a-b542-196aee77c4a5)

Will the benchmark be updated to remove all information about the VDD/VSS net, as in ISPD2024, or should we manually ignore it?

**Comment by cai-zhi-jie** [comment]
Besides, I also find the clk net in def.
![image](https://github.com/user-attachments/assets/a96bb08f-003f-4617-b0b2-15b54833f945)

**Comment by liangrj2014** [comment]
Thanks for the questions! You can ignore the the clock nets and power nets
