### ISSUE TITLE
Question about the Gcell grid and pin access point

### ISSUE THREAD

**Issue by cai-zhi-jie** [liangrj2014/ISPD25_contest#6]
As I noticed, the FastRoute in OpenROAD will build up the Gcell grid in its own way, not as defined in the DEF file.
![image](https://github.com/user-attachments/assets/8149b34a-5cbe-4625-97e8-032a0455ea21)
![image](https://github.com/user-attachments/assets/e4577c93-fa7f-49f9-9586-a0ca30497689)

Would you be so nice to modify the GCELL info defined in the DEF file to cope with the FastRoute pattern, and make sure the cap file is also align with the FastRoute?

Besides, would the pin access points in the cap file cope with those chosen by FastRoute?
Since the connectivity check will only accept the access point chosen by FastRoute.
![image](https://github.com/user-attachments/assets/1a17f919-8b26-4e31-af79-e661514eb82b)
![image](https://github.com/user-attachments/assets/22011a43-9ea6-496b-bdc5-07c889870b6a)

**Comment by liangrj2014** [comment]
Thanks for pointing out the issues! We will ensure that the GCell information defined in the DEF file aligns with the FastRoute pattern and that the pin access points in the CAP file match those selected by FastRoute. We are working on it now
