### ISSUE TITLE
Question about the number of output guide check

### ISSUE THREAD

**Issue by cai-zhi-jie** [liangrj2014/ISPD25_contest#7]
In the given example output guide, there are 120158 nets, while there are 138344 nets in the DEF file.

![image](https://github.com/user-attachments/assets/72ca227d-4f26-4d82-8bca-94338d11adcd)
![image](https://github.com/user-attachments/assets/956fb145-cd90-469f-bdb4-e7f771169179)

Since OpenROAD won't check the number of read-in guides, would there be an additional guide number check for a fair comparison?

**Comment by liangrj2014** [comment]
Thanks for the questions! Yes, we will implement additional checks to ensure the validity of the routing solutions.
