### ISSUE TITLE
Inquiry about Multi-GPU Availability for This Year’s Competition

### ISSUE THREAD

**Issue by 12zys** [liangrj2014/ISPD25_contest#8]
Hi, I noticed that last year’s competition provided 4 A100 GPUs as part of the resources. However, in this year’s competition PDF, it mentions that only one A100 GPU will be provided.

Could you please confirm:
	1.	Will multi-GPU resources (e.g., 4 A100 GPUs) be available for this year’s competition?
	2.	If multi-GPU resources are provided, will NVLink support be included for communication between GPUs?

This information is crucial for preparing our technical strategy. Thank you for your time and assistance!

**Comment by liangrj2014** [comment]
Thanks for the question! This year only one A100 GPU will be provided for each team. But we will consider setting up a special honor track for multiple-GPU solutions if we get enough GPU resources for the evaluation.
